# Generated by Django 4.2.27 on 2026-02-17 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculadora_Dieta_Ruminantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('nome_fazenda', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantidade_animais', models.IntegerField()),
                ('peso_inicial', models.FloatField(help_text='Peso em kg')),
                ('peso_final', models.FloatField(help_text='Peso em kg')),
                ('fator_ganho_peso', models.FloatField(help_text='Multiplicador para ganho de peso')),
                ('peso', models.FloatField(blank=True, null=True)),
                ('proteina', models.FloatField(blank=True, null=True)),
                ('energia', models.FloatField(blank=True, null=True)),
                ('fibra', models.FloatField(blank=True, null=True)),
                ('carboidrato', models.FloatField(blank=True, null=True)),
                ('gordura', models.FloatField(blank=True, null=True)),
                ('resultado_final', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Calculadora de Dieta para Ruminantes',
                'verbose_name_plural': 'Calculadoras de Dieta para Ruminantes',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
