# Generated by Django 4.2.27 on 2026-02-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('especie', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='cars/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_marca', to='produtos.marca')),
            ],
        ),
    ]
