# Generated by Django 4.2.27 on 2026-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_divisao_especie_linha_produto_alter_marca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ficha_tecnica_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/ficha_tecnica/', verbose_name='Imagem da Ficha Técnica'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/imagens/', verbose_name='Imagem do Produto'),
        ),
    ]
